# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20170918_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
